name: sc-gs
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.12.1=*cuda11.3*  # or any later versions
  - cudatoolkit-dev=11.3
  - pytorch3d=0.7.2=py38_cu113_pyt1121
  - pip:
    - numpy==1.22.0
    - trimesh==4.6.4
    - opencv-python==4.5.5.62
    - Pillow==7.0.0
    - PyYAML==6.0
    - scipy==1.10.1
    - tensorboard==2.14.0
    - tqdm==4.66.1
    - imageio
    - plyfile
    - piq
    - dearpygui
    - lpips
    - pytorch_msssim
    - matplotlib
    - scikit-image
    - git+https://github.com/Po-Hsun-Su/pytorch-ssim.git
    - ./submodules/diff-gaussian-rasterization
    - ./submodules/simple-knn
